--- #YAML:1.0
name:                Games-Framework-RCP
version:             0.03_01
abstract:            Generic video game tactics based battle system.
license:             perl
author:              
    - Jason Felds <wolfman.ncsu2000@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBIx::Class:                   0.0801
    Exception::Class:              1.23
    SQL::Translator:               0.08
    Sub::Exporter:                 0.981
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
